hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "79af2ab3cbd0b2fe620310f274b0f809f5332507d43c584f4ac097be0f8cd730"
metafile = true

[[files]]
file = "mods/accessories-compat-layer.pw.toml"
hash = "711a6cfc83cf149303b67b2d1e080d1ae4c6373cff928a2b96547f89f2fb9a7b"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "97befad2275e44c557794fbd321b154510279ce7906426607288062e096df86d"
metafile = true

[[files]]
file = "mods/almanac.pw.toml"
hash = "b4dd3b4217e0cf479207818b743a38f0566faa947e7b7d0b13c91e1a79d35e3c"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "b8b70f9719a562aa4c954f3bf51d6e7d23984f1efbff019c3fdeadca768d3b0f"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "d4838d91cd7747816ade0f2f4a46c701a53c3ef84cb278ec24e8f6fb828a85c3"
metafile = true

[[files]]
file = "mods/another-furniture.pw.toml"
hash = "60cd797dfe0cc7a6be4762120a05eed6e7068111b267e4da5993ef2229ce74dc"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "6adae9e2eefad5cf4d1729084860ec6877057dc0a1491d3ce243d7b14fb3d405"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "5601649308a7d9f1658a942bbd48d3bd899a81fabd4ea1296952b48474d1ee1d"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "6e39e7712a94830fbc2bd0b6ec73e03f54de5edfcca85da6e89a0021e9a3bf1a"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "5f32244bbf7f4864d6570bde7f7223655f52d5df455e7b9fe650b10dee42f830"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "941c3f358ef74f4fc99727e550106b8905d77cb4971321fd8ca4406e33b704a6"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "649ff7b3a2e701296e23d0842271a9b3cfcce6e81e7f7c24b558b2abeb0c358d"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "a4d21da45c40e8f1e3b76c9855ea3f1c15736cf2b12475e9de3efd05f8f48a8d"
metafile = true

[[files]]
file = "mods/christmas-delight.pw.toml"
hash = "d867e4743a955dbd92002ce3b38e7f2453d813fb2921b15d161c1fe84cffe441"
metafile = true

[[files]]
file = "mods/clickthrough+.pw.toml"
hash = "2cfaf0dcfad028db0e972f77946e71fd94376e8d70cba3d17d3abb484acf4ce8"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "fe84e2227c405bf9b735f01f307a01768784b9d49df82a13ecda3d3b6d198507"
metafile = true

[[files]]
file = "mods/cobblecuisine-delight.pw.toml"
hash = "9fe213dafbb17e6c00a547ef0cd7faa954a6aebba90a9fc9c8d08ef277bc9aea"
metafile = true

[[files]]
file = "mods/cobblecuisine.pw.toml"
hash = "dd9c84c3f22e37ee533990585112642b5c9a7ede61d29e5d13330a99b9a48b02"
metafile = true

[[files]]
file = "mods/cobblefurnies.pw.toml"
hash = "d5c2c194225075bcd748d812aa72bee771b9287851d0064cb25636415444cbf7"
metafile = true

[[files]]
file = "mods/cobbleloots.pw.toml"
hash = "489dfed279df684ed0677b5c28a5d0b3122e4324a9a9b85981861e5596a91026"
metafile = true

[[files]]
file = "mods/cobblemon-capture-pc-heal.pw.toml"
hash = "b83472c1b3c989ce3ba5ce18d34fc23c31463ef1de5a5dbf4128083158d2e1c0"
metafile = true

[[files]]
file = "mods/cobblemon-cobblestats.pw.toml"
hash = "d3ae6e38f29d487f1a0d17e11f1df4978dede56aae82c4de1e04a50a9cbe7be7"
metafile = true

[[files]]
file = "mods/cobblemon-integrations.pw.toml"
hash = "d627d0fb3f5c037ccc75d6504749bc9beed6b73068f740f79ece59fa4748508e"
metafile = true

[[files]]
file = "mods/cobblemon-mega-showdown.pw.toml"
hash = "41dc43f228ab5996e532233380548421ae9ecdbe750e3257f40a5552f92619e8"
metafile = true

[[files]]
file = "mods/cobblemon-pokenav.pw.toml"
hash = "eb51c053d004eafca2bca4cb91f9fedcee372fdf78c89fbbc6914c0fd103fc99"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "d0d21c8cd26fc4ddcdd03893e4b7ad5e1d1a4701a272f002f2932f9686770a6e"
metafile = true

[[files]]
file = "mods/cobweb.pw.toml"
hash = "49da1f100b78a8ad75c06dce97631944dfadc3598c0283d0217a80eb0b2e45b5"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "55176d940577a671525a837cb9db04380a0d3339f2b93314d5df9001653347f9"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "0fc78c92727b9b544fa152dd6ecfb3e1dca3a5d6a7ba56017c7b519215b875fb"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "eecdc8127f69c74ff55fd183d1f1d7d5ef3e714d73845a239fe9e086147a67b1"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "31535a06bf76553e83bd982eb3df9158b815cb7d0207a3fc719758d020d683b7"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "d5996c8fcf16081e29d914dfcdbff52472aa5407049d45763031026bd3dffac8"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "4effaea1cdc0ccd0de4a94ab435cc3cb22085933fca7e1dd35b9fb8953a1ce9e"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "e16d6a33648db866dedba7b9f76698025fb5ae4942bb0ea0ed5761135ed0cb99"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
hash = "76ab02862f59837b93cbfacfdfb722dfaf3fe5198db43ee884f61ad738a3f589"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "60e6720aafdfa3304b086f7465917179485a3b2463230505728bd24d54113de3"
metafile = true

[[files]]
file = "mods/emoji-type.pw.toml"
hash = "deb2af943ebcceb5b2d5d50c1c50b9d5921d75d30170dfe1f019a9c1e596ef60"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "054628ed76bd95bde1dbb4343721f3fbed87c8ad798ce99fc74b1171c39b6400"
metafile = true

[[files]]
file = "mods/extreme_sound_muffler.pw.toml"
hash = "29306f556497b5d1eb6113913dca0bdd7e52ee1a10a49eebce0eb7f216f01e6c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "debc633d962665af2873b7e4c74a5bd8da18d6a883971e73b9039f9612f457b7"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "14390472f86bf94cfd39b3e8cfb349f8c85017b4e370e92fc7c348b3b61b0acb"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "4387abb74dcfc93f9381c109fe76e7161ca7a91a1a642db4781b47f650c4ddab"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "2e705f04feb06d4340c59aebe8430c79a48635f6cd40b5c9f9ea7e4e6500721a"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "d8cdb69801ff0ffdf8c9cf6834dd592ca79ce1da139d303f8d17a62afec1abe2"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "43419651a1c8ee71281ce6d607fba199f0e87ba41f9725caa65b4dab2e589d49"
metafile = true

[[files]]
file = "mods/get-it-together-drops.pw.toml"
hash = "84e4e5d7adfa7d4a18bd1fb026d190824de8556fcc02036fea8f1a41563e1ef5"
metafile = true

[[files]]
file = "mods/harvest-with-ease.pw.toml"
hash = "a4db2300b1826a540ab97660a9830b1c2887454542f14ee4f10b64a7150a5e60"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "907ed71a8d572d5bc2a8f956b0b0d0fad37e1d5bdd48464041a76ef8fca79cb7"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "bb816aea0601d62b6d4dae506941da6220a0eea00b83d04f4ee099e031a52102"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "80858e1b1477432110b72aab33348635139d6e8fe7bc05db3ba00651de635720"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "e40ab1a8992d800199a6ac5a1a7411bae8141817f645c82c1fdc8c1381393f9e"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c4e45594c8d1ab3dacc3b49142f16fb253178dd31d97cc917bf4a4d54f21e081"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "98244dd3cf3bcc56edbc28e83f818a3a9e266b4a01d07d2c9550caf9193453ae"
metafile = true

[[files]]
file = "mods/legendary-monuments.pw.toml"
hash = "693c054ed12d18310be26745471103bb33041c9dffbb47def57623204e5c0030"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5564dbbe8adc0ba450afc6a1c3eef82f183a53ede5f3b1de0bc6ca320aadc5e9"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "46e175b662617498d6f250e57f3f66b1b39a40252933b3466e1ff6a7f6209725"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "072fbe097e33846a72d22ce9d4457bab1acfb4b3af4bf79feea70270834de025"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
hash = "edde86d78cb403fbe13d3d0008cd94fbafcef5dfeb91874da016d6a796b446de"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "d12b136e07f6f83a1e199aabe430426d19702c9f69e55731092b5d5c2f3fb69f"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b9651d06e56ad51c1cdcf4b03b6a34328b7dc941f263ff92b189ee26a47cc224"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "f77a1de001da650d5745acd2b410d6729bf61282d91cf3e8883e891f9707f85a"
metafile = true

[[files]]
file = "mods/more-delight.pw.toml"
hash = "f1a7bff7a5ed9e9f88a02786b33737a99852a5e4f5e6c05b6269a63daf9f1e72"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6be43ffc708ac329843aee99ededc692ecf6461ee8e409d373f55fc5494db5af"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "04074b9045c0d90c6b93e85ae97b0e5f8c8eab2b88c509381bc52bf5cb7a71b8"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "f53b91397b8a969e843af8772db448ab1c9bc556233a3b26266c52cfa77950fe"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "f3c5cb21ff2e78c7e8cdbd14d1535e6edd464d5a436dbfa4e60b8ea91374674d"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "dcc936d7bd32a86ce63fa3bf013864a4e2ed979cb126a915153ac70ce5e5671f"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "fa28010fe3ba32b1f3e9aed4c432c359ebc54cfbf03196961c66461597f4188c"
metafile = true

[[files]]
file = "mods/open-loader.pw.toml"
hash = "5ea6f9fdefad7193d99da78fd4aebb62957ff5ae749bc3ea67abbe7272bcac63"
metafile = true

[[files]]
file = "mods/overflowing-bars.pw.toml"
hash = "88c410db35e0f78c6c699dbd801215407d590b49fb3bbfd0d2094b5def538b4d"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "60a3d23eb73106ecb6ba5a391d4539e3557cbd9b1f3611a2de08052155d78b3a"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "f1746f7abc78b5a149212d295b903cfc232477b1abd9e2050e5d4af3acc530b5"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8a64fdd5384cd26c91475a423f3bec24dd4d98796df7683a5070ef105d421ba4"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "122659d423e8fe5c47b4121bf382e5ceea0ea2c644cd0a08d577cf58ef55d495"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "44a6662d6ac604b2173a8bc426a10c0d621c8ba99d37d1b72525c140c42cb358"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
hash = "a717ad1dd50748d87bb8a1126054933bf59617238f968acaa1844e71aed29585"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "d3f633dd12cd039a4e58dd398d1c80a324b0d78b9da5b3972b69640bfed211ed"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "6b91f46291891e725189b0bd54d0db0f66925b1e785bdfa737592dfcf41a79a3"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "59943cbd2c0e4e90f65002e17704bca571acb09b095fc69fdf430df4bfd42870"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "86ff9b67d90f046045619aa571df7bad909e480711c5d8b8967e3efca84ad16a"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "8302da862578554b012b2cfe58a3c1e75b514d09f94d842e7303be41a2157aeb"
metafile = true

[[files]]
file = "mods/show-held-items.pw.toml"
hash = "bf260f5c1ee56f7c499ed6ae04a985fd29a974ba135c0deebff2e5a2b607e39f"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "272b27d64cd27b909567437683287909b35de9f78db27214efb1d5e4334f9f82"
metafile = true

[[files]]
file = "mods/sirdoof.pw.toml"
hash = "be4c9bb7ca29a45c57b39d194e0967c877b9cef7b71f20c3a5cad6baefb74b59"
metafile = true

[[files]]
file = "mods/sodium-extras.pw.toml"
hash = "247d0c160732895f6bc4a3cf0f0ccf74f55fc9ea67800e87495b8d817093fbbe"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "461adc31ce2b89cafc5ad2e846b482c68529231ac1d907e39ec62458b22e6b3e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-(unoffical-fabric-port).pw.toml"
hash = "a4eebb2bda9daccc5444b8bd2d91f4ee8ce2325dd51436cb785ca33530b98ecd"
metafile = true

[[files]]
file = "mods/sophisticated-core-(unofficial-fabric-port).pw.toml"
hash = "3dae8bafdd462a599adbf8d41edb8ad3000ba440065fc026f059a76ec336f6f8"
metafile = true

[[files]]
file = "mods/sophisticated-storage-(unofficial-fabric-port).pw.toml"
hash = "6b4e996f56225b0a8673741480dd7dfdcd2cb089310c6f25dee8ba49a6ff6c95"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "4ea85fa7d750bf5a167fe9652f2ac896d12ab068dacb8b04539e316ba5b74042"
metafile = true

[[files]]
file = "mods/storage-delight.pw.toml"
hash = "570a995d2e20eed34c5b708f09b4b02fea827054a32df7bb55257719b8cc849e"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "8e009ac87710fbd8f5990285d36ab2b4755e932664ca1bcb9cdfac116d6e3b6d"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "97df1677b1871339d75f5244c74446990a6109186f3b0478961181352b23ad8d"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "d3f1d02d785b5dd6d53ab6b38a903558b36e1e97dfb4e64b76375c75e26e90bb"
metafile = true

[[files]]
file = "mods/trailtales-delight.pw.toml"
hash = "7b83fb97e1b10d79facae8c65138bd3c915ff25bba39761f0d04639f2c4cd37a"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "860812150cb54f0d9ee1bce7b72798b6cc5f752bb05709f0c60231d054ec281d"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "a6fa6d762556487f3ec34b332bbf3e6ad3758d1ecd046026f1a3dfd6f48d17d7"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9183120fa9e7a6f363a82dba25f1e0073a4f3889ef63c4b4818fd6d68fc12b0e"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "2180627da1fb1dff2a6d0e8b66bea618aed4c28959ddcbb4e4b12a4a4d50a521"
metafile = true

[[files]]
file = "resourcepacks/cobblemon-interface-modded.pw.toml"
hash = "f812bf391fc0a1577007d566a1c87c4aa65286f56880b05552f186d28ebced52"
metafile = true

[[files]]
file = "resourcepacks/cobblemon-interface.pw.toml"
hash = "252ea5b173528625a9e30c39598d80c1a18021f6695c822fece342c88db86ea2"
metafile = true

[[files]]
file = "resourcepacks/e19_cobblemon_minimap_icons.pw.toml"
hash = "7925ee20a72c3400d470b982fcd788808d25e5446b4d456afad03da484456874"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
