hash-format = "sha256"

[[files]]
file = "mods/almanac.pw.toml"
hash = "f69fb66341fa0ac51d6ab8637efa6f68fa97038169a186975bdaff19d7139fbb"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "61ab7794e676f45410312efe39c2cc6edf5835f4d7fa5ab685be0c0e4b78f984"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "8dde79bba7cacff03bd65e6b896d939fc7c2e02a86c23b693d2e0b678672bdd2"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "95322b6e88dbeba91b5e7a30d6bd011629124ae8aef5bf1b7d1304f12bd4619c"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "6cd235030774b3cfab54145cf616ab47b0afa57cacab75ede94c2682c9450ce9"
metafile = true

[[files]]
file = "mods/c2me-neoforge.pw.toml"
hash = "8e4abfea25c864a1a1bd31948f95020b3486370e53d2f53bcc4f869ad95c4536"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "8629fe0739a2243641a1a00b103682bcb2741a9295f9eac4c2a2135a867f8442"
metafile = true

[[files]]
file = "mods/clickthrough+.pw.toml"
hash = "ffb0861ae37abc292e61208c8b7826b7b8287b24c07419083d4bb4ac109da4ee"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2acaff560bbda5741538528a2967355ec86a8f7564adba0b2316989c66892374"
metafile = true

[[files]]
file = "mods/cobblemon-integrations.pw.toml"
hash = "33e622b555cb9a87a5f1845df1dc25d5827428c23892ee6f98300591b4e2500d"
metafile = true

[[files]]
file = "mods/cobblemon-pokenav.pw.toml"
hash = "132dbb456d882d92aa41556558e5a5c2ecdded4777390ddecf8f5678d804afb8"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "626d8158ec0e84758abfb66ad1ae4e53f353f995bda5ae52b2b0b662f3420248"
metafile = true

[[files]]
file = "mods/cobweb.pw.toml"
hash = "23f681379a3e647a59f0749d25f2ce0725d4afafeed41871c5c87f2658d13a72"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "5e0a875282f4abed66a2cccf7929488ebb5e88447d2bb3369e8ddc728fc66fc0"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "af4dc4828902eae1784568632a749fe9a442943f1570ac0ba3ea75e79934be41"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "65c8086d2ec3d39acc7bd36c7a0306ccc43b602b38fa07d13291bc478ef7dfff"
metafile = true

[[files]]
file = "mods/crafting-on-a-stick.pw.toml"
hash = "d69ef8c4975dbafb2703abfd81932e21dd9266ab5640a07f8563ffed1caf243b"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "4c16ee75d3b04443e96d854eec79344293963e9f4beaaf8e7215023e8ef53b88"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "975f1280c712d2e86dd4ecddf89c516afbf3f1fb684499d3e5c71fc666c4888c"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "0603752f5a3db14a380597c84cdb80c3b66564a69d8c7f5c4f1d35c4f2a32924"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
hash = "ae513cc0ae6e28e70e402bf9a1e5300f991c81b07539e4f7e3aac1e07298eead"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3443f52ef7c1f80ae1cedf459b23c38ac78dbe547cf2cc047e62d0cb2331c808"
metafile = true

[[files]]
file = "mods/extreme_sound_muffler.pw.toml"
hash = "5916832d06322a7a54d87e1fe47da5009daed0213510573d9c311c5ceefa9937"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "2741b6724a6c7d625c1c9e647a8d20ab89cd4a3975c18706da30771754c00510"
metafile = true

[[files]]
file = "mods/fastquit-forge.pw.toml"
hash = "574e4be5a4194cf6a44a5d064e3734dfbaac911c3caebfdf722ed7c35ff5215e"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "ec1bd5b80399287ca33a113086bee9d5697b7e673c9f593e5a1aeca4c9bad4c9"
metafile = true

[[files]]
file = "mods/functional-storage.pw.toml"
hash = "bf87620865e88ba85547d050f09c579e991ed1f80a05058ff86598c61e1d057d"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "11c4ac6932c14f3ad5a2c63d7f39eee1e9a2a91ffc079d5bd917c9aa381abdfb"
metafile = true

[[files]]
file = "mods/get-it-together-drops.pw.toml"
hash = "82a892755a825ac7724c84c063cef2f884fc8c3b36ac1da8bb02dbbd76af58aa"
metafile = true

[[files]]
file = "mods/harvest-with-ease.pw.toml"
hash = "a8c6a45895b59f2a00c108a5247de7eb15083a0bd835ed10c850ca22f81504ba"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6bdf101d3d5ec8729a8095d5853f80eb925a47c889cd10de6704b20cc7f3c73e"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "5d49dd7272a1418fabed10e3ef9b5c79c3bbb9205d83e79e301c16ad0a0e89e6"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
hash = "98244dd3cf3bcc56edbc28e83f818a3a9e266b4a01d07d2c9550caf9193453ae"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "e8c20c0c77e5df58d1386d8190ee16a957d78d62d361469db0b0c29458bf1e84"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7b8e8af83e8583adc91b2d859e5355f1bd0516a346d2584b8b01c004467d18af"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "edc75ace846ae34c1cb4cf4a44106e1fb035b1eee0432765a716098c9a4b5823"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "13c7c076a8b905ed483f64207eababf1fc922e440271809085d14adb4f433a3f"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
hash = "ad52f42cb5e9080cd493d1e7b2acfbc6c662ece8f094288604d54a224ce0e440"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "6f0dcbcffd4400c6cef07f1eeb48cdc25bac0fa01270936feab4c549aff4738e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "eae3c14c915400de36bf547550f630de727bbf48ae0ce719b99b2ff50ceaab0d"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "78f6a760d66709335b8bc92561589b0aba25873ef77f4cd1cdec570416ae9c6b"
metafile = true

[[files]]
file = "mods/more-delight.pw.toml"
hash = "26037d30e6793c772f46bbd1f4a6bc1b07806a7f611fe9c42f21a95902a4d577"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "91696791780719730cb8826de0c53d8513a7c2b320f7d641dbeb6ca974e5cec3"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "abfc8909de1c851ccf4ef296e05d1017332a21fef76fd1f938828fcff925115b"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "d424a9260ef51bc102e56f0423d91dfabb739ccca8a86eb1c450ea631b739280"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "09ba6db54e6f13fafa1e12a9adcd83db9137617d631288579f520ab11b4bfe9a"
metafile = true

[[files]]
file = "mods/open-loader.pw.toml"
hash = "904c4adb3f8087a2c5381efd5d210183484934540372a5c839ab4790325e5cff"
metafile = true

[[files]]
file = "mods/overflowing-bars.pw.toml"
hash = "cb40fc0e1e0a3338d57b34a5ba2612ae9a9f0e32619695c4da637a98b4e52cf3"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "573f309a1bd1c410d149b6830aeddee7313e0698ac249a94f63a7e95c0eb146e"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "152769b5dfbb92a836634e315898b23b6a555c60b6f05ddf38c00085f2b784f6"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "c99c5bac469e8d6ece5aae80f08635e3bbb8367f0c586b6288573c725faefe69"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "6812c3faa178cd48c65c5b8e7aeef50bc0b63d8e3b2117065d6179a43d8d3649"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "6b91f46291891e725189b0bd54d0db0f66925b1e785bdfa737592dfcf41a79a3"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "b78044fd79ce21750d05dc61b6aede33c4b87cdc16a26f5aff472d4f73ab623c"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "2507dd9242e994ec7a0b21255b0b51a91bf9e0e51b060defe7bf7f8fa1f04b53"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/simple-backups.pw.toml"
hash = "00c92d192436a4dde9a7cb2ba3be298bbe06bc6076d2c28332e499ae7dde2bc0"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "82fa5e74cae0b3f0199f9822f62a976da2dc6ee03deb543d537ce55d36b11fcb"
metafile = true

[[files]]
file = "mods/sodium-extras.pw.toml"
hash = "02b29315d2ec0d055d0ebba1f36879da5bcacc823328a668c7e7340fb2cb03d4"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "d193173f0f5dfb4a921d44e29e8d5cee656dd3a40872939069715bb482b66fc9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "a2028f1fdc803760a29877b07b2958cecdc6402eb946f9d5a0fff9fe72b8671d"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "8ed3c58f23d9255343a590b90e1216ac58142b920c9bffdd14c7fdc32e3ee002"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "cba519b3e00eb2e03b3532664d1d99de5a0dd306c6ce4b49dcd462a58d4c187b"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "258a77de0a6db4c9ab045cbb240bcf4eac0dbbca3f6bc981fb461e55c247f23f"
metafile = true

[[files]]
file = "mods/storage-delight.pw.toml"
hash = "0ccdb1ac3f7fffacc28ffa235bdf7e37105c088095f96b6e3fc9748d64328b94"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "2e4c8891ec22ca246b414728493ff52fe177bc9c4369ed23a5a80e8332e79c67"
metafile = true

[[files]]
file = "mods/titanium.pw.toml"
hash = "44ecdae2df678c7cb008e48a3a50079203045a03d16e49aa74637fae97630ce7"
metafile = true

[[files]]
file = "mods/trailtales-delight.pw.toml"
hash = "bb39209a9ee057bf7606396c9c01f27ad980218b95d01d44089cadab1063a964"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "12d9283f643e9b8f85368fccf82f328c471c043fcf06fe08dea6c034be3b0c22"
metafile = true

[[files]]
file = "mods/zume.pw.toml"
hash = "417f2ce9f6018e0ce5b548c4e3212abe3d74878654dd2a8a057d54c334d5b188"
metafile = true
