name = "E. Coli"
author = "AmeMeida"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87c2d248f508a65460238fec3b11971ea2cee1b75bdb25b588f4a9d3fe4bb720"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
datapack-folder = "config/openloader/data"
