name = "E. Coli"
author = "AmeMeida"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58d1a080388cf11abbcf4bf13d7ef580cee74a6cbac13611d21d69b2d28c580e"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
datapack-folder = "config/openloader/data"
