name = "E. Coli"
author = "AmeMeida"
version = "2.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9553a045d9d1bc6de640be2a4f1877437964a7bc25bcadb045c34e4eaad6e99"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
datapack-folder = "config/openloader/packs"
