name = "E. Coli"
author = "AmeMeida"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b07b2cc20cd41b89ebd8ab551718fe9dcb462c1a2d512c10331fff7b754d4c22"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
datapack-folder = "config/openloader/packs"
