name = "E. Coli"
author = "AmeMeida"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e5d9672fca10e99e7f9fc0849ac253c2bbc089735d3f6b9b7c5f9f35bd34b24"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
