name = "E. Coli"
author = "AmeMeida"
version = "2.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edd7b8cf30dbf9df76a069302a5cca93d0725a986e45f53e0ab1684db8c2f09e"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
datapack-folder = "config/openloader/data"
