name = "E. Coli"
author = "AmeMeida"
version = "2.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2b3a242a93c66c146dd1007bb0528ddb15ba02b77606794ad6b90f9cd060ec6"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
datapack-folder = "config/openloader/packs"
