name = "E. Coli"
author = "AmeMeida"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "638e53c415684b63d70436a3e27b807bba2d832963ea5244600a71b453dec5c1"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
datapack-folder = "config/openloader/data"
